title = "Kubernetes Community Days"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://kubernetescommunitydays.org/"

[params]
description = "A series of conferences devoted to the cloud native and [Kubernetes](https://kubernetes.io) ecosystem"
font_awesome_version = "5.8.1"
sans_serif_font = "Lato"
allowed_event_pages = [
    "sponsor",
    "speakers",
    "venue",
    "program",
    "contact",
    "code-of-conduct"
]
twitter_handle = "kubeconio"
tweet_limit = 5
hero_banner = "hero-banner.jpg"

[params.hero]
logo = "kubernetes-community-days-white.png"

[params.navbar]
logo = "kubernetes-community-days.png"

[[params.fonts]]
name = "Roboto"
sizes = [300,400,600,700]

[params.social]
twitter = "https://twitter.com/cloudnativefdn"

[[menu.navbar]]
name = "Organizing"
url = "/organizing"
weight = 1

[[menu.navbar]]
name = "Code of Conduct"
url = "/code-of-conduct"
weight = 2

[[menu.navbar]]
name = "Speaking"
url = "/speaking"
weight = 3

[[menu.navbar]]
name = "Sponsoring"
url = "/sponsoring"
weight = 4
